name: Mabl Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-mabl-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Mabl Tests
        uses: mablhq/github-run-tests-action@v1
        with:
          application-id: E1pE21Ob0r14VaupJf8k8g-a
          environment-id: kQwkVWlhF876qUtB2ginoQ-e
        env:
          MABL_API_KEY: yNX46537JBAbuyc9hFYVfA